# tasks/install_docker.yml

---
- name: Gather information about installed packages
  package_facts:

- name: Install Docker prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
  when: ansible_facts.packages.docker-ce is not defined  # Only add the repository if Docker isn't installed

- name: Update apt package index
  apt:
    update_cache: yes
  when: ansible_facts.packages.docker-ce is not defined  # Only update if Docker isn't installed

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
  when: ansible_facts.packages.docker-ce is not defined  # Only install if Docker isn't installed

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes